### ISSUE TITLE
Add a Discussions page to the repository

### ISSUE THREAD

**Issue by PipKat** [ansys/pyensight#281]
### Description of the modifications

When adding links to cheat sheets, I found that this library and the PyDynamicReporting library don't have "Discussions" pages for the respective repositories. The next to last paragraph in the "Documentation and issues" section in BOTH the README and the overall RST file for the docs should look like this for the PyEnSight repo:

```
On the `PyEnSight Discussions <https://github.com/ansys/pyensight/discussions>`_ page or the `Discussions <https://discuss.ansys.com/>`_ page on the Ansys Developer portal, you can post questions, share ideas, and get community feedback.
```
However, because there is no Discussions page for this repo, in [PR #282](https://github.com/ansys/pyensight/pull/282), I had to leave out the beginning of the preceding sentence.

**Comment by mariostieriansys** [comment]
@PipKat did you add the discussions page? I can see it on github, so probably we just need to add the link as you mentioned

**Comment by PipKat** [comment]
@mariostieriansys I did not add it--but I'm glad someone did. Tomorrow, I will add it to the README and overall index.rst file as indicated in the issue and then close the issue. I'll ping you on that PR. Thanks!
