### ISSUE TITLE
listobj.find_objs broken

### ISSUE THREAD

**Issue by mariostieriansys** [ansys/pyensight#352]
### 🔍 Before submitting the issue

- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### 🐞 Description of the bug

There are multiple issues:

1) If the types argument is None, an error is reported where "types" should be a dictionary. First of all, types is a list object (the error reported needs to be fixed in EnSight). Also, it is legal to pass None so that EnSight should look for the objects on all the classes available

2) One cannot pass a PyEnSight type but has to pass the EnSight type, since it is executed remotely. There needs to be a sort of mapping

### 📝 Steps to reproduce

Just run find_objs

### 💻 Which operating system are you using?

Windows

### 📀 Which ANSYS version are you using?

24.2

### 🐍 Which Python version are you using?

3.10

### 📦 Installed packages

```shell
ansys-api-pyensight==0.3.4
ansys-pyensight-core @ file:///D:/pyansys/pyensight/dist/ansys_pyensight_core-0.8.0.dev0-py3-none-any.whl
asttokens==2.4.1
atomicwrites==1.4.1
attrs==23.2.0
black==24.2.0
build==1.0.3
bump2version==1.0.1
certifi==2024.2.2
cfgv==3.4.0
charset-normalizer==3.3.2
click==8.1.7
colorama==0.4.6
coverage==7.4.3
decorator==5.1.1
dill==0.3.7
distlib==0.3.8
docker==7.0.0
executing==2.0.1
filelock==3.13.1
grpcio==1.62.0
identify==2.5.33
idna==3.6
iniconfig==2.0.0
ipdb==0.13.13
ipython==8.20.0
jedi==0.19.1
matplotlib-inline==0.1.6
mypy-extensions==1.0.0
nodeenv==1.8.0
numpy==1.26.4
packaging==23.2
parso==0.8.3
pathspec==0.12.1
pillow==10.2.0
platformdirs==4.1.0
pluggy==1.4.0
pre-commit==3.6.0
prompt-toolkit==3.0.43
protobuf==4.25.3
pure-eval==0.2.2
py==1.11.0
Pygments==2.17.2
pyproject_hooks==1.0.0
pytest==7.1.2
pytest-cov==4.1.0
pytest-mock==3.10.0
pywin32==306
PyYAML==6.0.1
requests==2.31.0
six==1.16.0
stack-data==0.6.3
tomli==2.0.1
traitlets==5.14.1
urllib3==1.26.18
virtualenv==20.25.0
wcwidth==0.2.13
```

**Comment by randallfrank** [comment]
This issue was fixed in ansys-api-pyensight PR 23.
